### ISSUE TITLE
swiftshadow takes over logging

### ISSUE THREAD

**Issue by toneman77** [sachin-sankar/swiftshadow#14]
I do not know how but since I added swiftshadow to my codebase my own logging stopped working.
In the file where I import swiftshadow.swiftshadow I do

```python
logging.getLogger().handlers.clear() # <-- first attempt at a workaround
logging.basicConfig(
    filename=script_dir + "/log/mylogfile.log",
    level=debug_level,
    format=(
        "%(asctime)s %(levelname)s " 
        "%(message)s"
    ),
    datefmt="%Y%m%d %H:%M:%S",
)
logger = logging.getLogger("mymainlogger")
logger.info("I am info logging!") # this usually ends up in mylogfile.log
```
As mentioned this setup worked fine before using swiftshadow. 
Now my mylogfile.log stays empty and all I see is swiftshadow output on stdout.

Any idea how I can make my logger work again?
I tried finding your logger with logging.root.manager.loggerDict by to no avail :(

**Comment by sachin-sankar** [comment]
I have alos observed this issue. Will release a patch to revert the new logging functionality as there is not a lot to log in the current moment. Print should suffice

**Comment by toneman77** [comment]
> I have alos observed this issue. Will release a patch to revert the new logging functionality as there is not a lot to log in the current moment. Print should suffice

will it be possible with the patch to still install it via requirements.txt and patch afterwards?

**Comment by sachin-sankar** [comment]
The patch has been released 
```py
pip install -U swiftshadow
```
To upgrade
Or set the version to `0.2.3` in `requirements.txt`
