### ISSUE TITLE
Https protocol not working for selenium

### ISSUE THREAD

**Issue by tvaeyens** [sachin-sankar/swiftshadow#25]
I am trying to get a proxy server IP for selenium:

```python
proxy = Proxy(autoRotate=True, protocol='https').proxy()
print("Proxy response:", proxy)
```

--> Proxy response: {'https': ''}

```python
options = webdriver.ChromeOptions()
service = Service(executable_path=chrome_driver_path)
options.add_argument('--proxy-server=%s' % ip)
driver = webdriver.Chrome(service=service, options=options)
```

When I set the protocol to http, I get an IP in the dictionary. Any ideas what I am doing wrong here?

Thanks!

**Comment by sachin-sankar** [comment]
The return type is in dict so that you can use it seamlessly with the python requests module. For selenium try https://stackoverflow.com/a/40628176
